name: auto-release
description: "Crea un release y sincroniza las ramas develop y beta al hacer merge a main"
on:
  pull_request:
      branches:
        - main
      types: [closed]
jobs:
    build:
     if: github.event.pull_request.merged == true
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 INSTALANDO NODEJS LTS
        uses: ./.github/actions/setup-node

      - name: ✏️ CONFIGURACIONES PARA FIRMAR COMMITS
        uses: ./.github/actions/git-config
        with:
          username: ${{ secrets.USER }}
          email: ${{ secrets.EMAIL }}

      - name: 📝 CREANDO RELEASE
        uses: ./.github/actions/set-release
        with:
          releaseType: ""
          branch: "main"

      - name: 🔄 SINCRONIZANDO DEVELOP
        uses: ./.github/actions/update-branch
        with:
            branchOrigin: "main"
            branchDestiny: "develop"

      - name: 🔄 SINCRONIZANDO BETA
        uses: ./.github/actions/update-branch
        with:
            branchOrigin: "main"
            branchDestiny: "beta"
