name: delete-branch

on:
    pull_request:
        types:
            - closed

jobs:
    delete-merged-branch:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - name: ✏️ CONFIGURACIONES PARA FIRMAR COMMITS
              uses: ./.github/actions/git-config
              with:
                username: "Jmendez-Bot"
                email: "jorge.mendez.ortega@gmail.com"
            - name: Checkout repository
              run: |
                  BRANCH_NAME=${{ github.event.pull_request.head.ref }}
                  echo "Branch to delete: $BRANCH_NAME"
                  git push origin --delete "$BRANCH_NAME"
